language: cpp
compiler:
  - gcc
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:apokluda/boost1.53
  - sudo apt-get update
  - sudo apt-get install -y g++-4.8 autoconf-archive libleveldb-dev libsnappy-dev libboost1.53-dev libgoogle-glog-dev
  - export CXX="g++-4.8"
before_script:
  - ./bootstrap.sh
script:
  - ./configure && make && make check
